version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: testDB
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Password"
      MYSQL_DATABASE: "library"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "Password"
    volumes:
      - ./test-db:/docker-entrypoint-initdb.d
